### ISSUE TITLE
abc1600 no longer boots into abcenix after M68008 refactoring

### ISSUE THREAD

**Issue by curt-coder** [mamedev/mame#11288]
### MAME version

0.254 (mame0254-326-g78661e9aa92)%

### System information

macOS 13.4, Finnish

### Emulated system/software

Luxor ABC 1600 (abc1600)

### Incorrect behaviour

After commit `78661e9aa92c7e43c9a96039e7dfb3dabc79a287` booting into `abcenix` throws a panic inside the emulation. 

Also `emu.keypost` from a LUA script has become unreliable, skipping some letters.

### Expected behaviour

- system successfully boots into `abcenix` as before commit `78661e9aa92c7e43c9a96039e7dfb3dabc79a287`
- key input from LUA script works reliably as before commit `78661e9aa92c7e43c9a96039e7dfb3dabc79a287`

### Steps to reproduce

`./mame abc1600 -flop1 abcenix`

Enter these commands inside emulation:

```
mf(2,0)
mf(2,0)
abcenix

```

### Additional details

Sample LUA script

```
function keypost(keys, len)
    emu.keypost(keys);
    emu.keypost('\n');
    emu.wait(len);
end

abcenix = coroutine.create(function ()
    mf2 = manager.machine.images['5a:2:525qd'];
    mf2:load_software('abcenix:flop1')

    emu.wait(1);
    keypost('mf(2,0)', 22);
    keypost('mf(2,0)', 3);
    keypost('abcenix', 95);
end)

coroutine.resume(abcenix);
```

**Comment by ajrhacker** [comment]
I think this regression *might* have the same cause as the unresolved regression in hp_ipc (q.v. faffe08074888e4bdc36607d00de451c5c230b52).

**Comment by galibert** [comment]
Could be.  hp_ipc is fixed now (thanks ajr), can you check whether abc1600
likes it better?  Commit is f4dccdc1c5bd573a19915545967fe74cfb00f8f9.

  OG.

**Comment by curt-coder** [comment]
Still getting the OS panic with https://github.com/mamedev/mame/commit/f4dccdc1c5bd573a19915545967fe74cfb00f8f9.

**Comment by curt-coder** [comment]
This happens because RTE triggers a bus error (handler at 006DA):

Musashi

```
004D0: rte
08000: move.b  ($28,A3), D0
```

New core

```
004D0: rte
006DA: movem.l D0/A4-A5, -(A7)
```

Apparently the 68008 core switches between supervisor and non-supervisor mode prematurely between the byte reads.

**Comment by curt-coder** [comment]
Fixed in 1a427e8e8dc986b486189f3e086356f4dff229fb
