### ISSUE TITLE
MameUI 0.176 Controller Options In game UnSeeable

### ISSUE THREAD

**Issue by shinra358** [mamedev/mame#1249]
Going into the options to change your controller config is impossible because once you select the options to do so, the box goes offscreen and you can't see what you are doing.

**Comment by Tafoid** [comment]
Has already been Reported, Logged, and Fixed in Current GIT sources.
http://mametesters.org/view.php?id=6335

**Comment by shinra358** [comment]
http://www.emucr.com/2016/08/mame-git-20160827.html

Just downloaded a new version and it is still happening. What's the deal?

**Comment by mamehaze** [comment]
well for a start, you're using a build from Emucr

Never use anything from emucr, they ship known broken builds all the time, don't compile things properly (often not doing full rebuilds when they're needed) and never seem to package anything properly.

if it can be reproduced NOT using a build from Emucr, then it might be interesting, but Emucr are so bad that issues with their builds can't really be considered.

**Comment by shinra358** [comment]
where to get builds like these already compiled? I've already deleted the tools necessary to do so a long time ago because never could get anything to compile right and I just gave up lol.

**Comment by mamehaze** [comment]
for 32-bit I'm not sure, there is a site doing a good job of nightly builds, but they only do 64-bit.

**Comment by shinra358** [comment]
Great! Which site would that be? My OS is 64-bit :)

**Comment by mamehaze** [comment]
I found
https://build.btolab.com/project/mame/
to be trustworthy, properly built, and properly packaged.

**Comment by shinra358** [comment]
Appreciate it! That did the trick.

**Comment by shinra358** [comment]
Whelp, most is fixed. But it is still a problem with 'Input General' > and everything below 'User Interface' is still broken.

**Comment by mamehaze** [comment]
maybe the bug causes some old config files to become corrupt then?

are you installing to a fresh folder to avoid that?

the reason for the bug occurring was rather straightforward and a fix was definitely put in, and I've tested the builds from that site without an issue.

**Comment by shinra358** [comment]
extracted the data from the windows version from that site you linked into a fresh folder. Put 1 MameUI64.exe into said folder. Put one rom into the roms section in that folder. Audited that rom. Did nothing else but turn the game on and press tab. Goes into the above stated settings and it's still offscreen.

**Comment by Tafoid** [comment]
It sounds like MAMEUI64 is the same binary you had before?  That site does
not make integrated Windows UI builds.  It sounds like despite downloading
multiple standalone binaries, you are still running MAME64UI every time
which hasn't been updated and has the same behavior as it did when 0.176
was released.  Am I right?

**Comment by Robbbert** [comment]
Using the same MAMEUI64 as before won't solve anything. You can either try MAMEUI32 (should at least solve the disappearing box problem), or get a daily build from the site mamehaze suggested earlier.

**Comment by mamehaze** [comment]
Well no.. upgrading the MAME version then using your old mame exe isn't upgrading the MAME version at all, so of course you get the same bug..

**Comment by shinra358** [comment]
MameUI is just that. A UI. Why would a UI have anything to do with the new mame build in regards to this? It's just a frontend and SHOULD have nothing to do with how the program mame acts internally right?
Used the mameui exe only from this site: http://www.mameui.info/
with the new update and same thing happens. MameUI64.exe and mame.exe are different things that sit in the same folder.

**Comment by cuavas** [comment]
MAMEUI is not just a UI, it's a MAME derivative with a built-in UI.  It isn't using your new copy of MAME.

**Comment by shinra358** [comment]
Ok. Opened it with a bat file and it works correctly.
