### ISSUE TITLE
Exception when using File Manager to switch ROMs

### ISSUE THREAD

**Issue by Tauwasser** [mamedev/mame#2415]
When starting a machine with a game loaded via command line and then trying to switch to a different game using the File manager, an exception is thrown. Steps to reproduce:

1. start a machine using command line, e.g. `mame gameboy 4in1_002`
2. Press TAB
3. Select "File Manager"
4. Select "[file manager]"

Mame will now crash with the following exception (written to command line):

> Caught unhandled St12length_error exception: basic_string::_M_replace_aux

However, sometimes there will be:

> -----------------------------------------------------
> Exception at EIP=000007fefd02974f (not found): ACCESS VIOLATION
> While attempting to read memory at ffffffffffffffff
> -----------------------------------------------------
> RAX=000000007fffffff RBX=ff002950ff00356d RCX=ff002950ff00356d RDX=000000007fffffff
> RSI=00000000e7002341 RDI=000000000000fde9 RBP=0000000000000000 RSP=0000000000227bc8
>  R8=0000000000227c60  R9=0000000000000000 R10=0000000000000000 R11=8101010101010100
> R12=0000000000000000 R13=0000000000227e20 R14=0000000000000000 R15=0000000000000000
> -----------------------------------------------------
> Stack crawl:
>   0000000000227bc0: 000007fefd02974f (GetSystemDefaultLCID+0x006f)
>   0000000000227bf0: 000007fefd029727 (GetSystemDefaultLCID+0x0047)
>   0000000000227cd0: 000007fefd02979a (GetSystemDefaultLCID+0x00ba)
>   0000000000227d10: 0000000076df500b (MultiByteToWideChar+0x001b)
>   0000000000227d80: 0000000000b19c85 (not found)
>   0000000000227db0: 0000000000847c2d (not found)
>   0000000000227ec0: 000000000060c393 (not found)
>   0000000000228000: 000000000060fdee (not found)
>   0000000000228060: 00000000005d41cb (not found)
>   0000000000228150: 00000000004f17ad (not found)
>   00000000002281d0: 00000000007b5573 (not found)
>   0000000000228250: 000000000078915b (not found)
>   00000000002282c0: 000000000078cf45 (not found)
>   0000000000228360: 00000000007846b2 (not found)
>   0000000000228450: 000000000073d62b (not found)
>   000000000022f200: 00000000004bd9ff (not found)
>   000000000022f4c0: 000000000051d0d7 (not found)
>   000000000022f620: 000000000051d60b (not found)
>   000000000022f680: 00000000004bba77 (not found)
>   000000000022fdc0: 00000000004082e7 (not found)
>   000000000022fe50: 0000000000b1a26e (not found)
>   000000000022ff20: 0000000000401410 (not found)
>   000000000022ff50: 000000000040153b (not found)
>   000000000022ff80: 0000000076df59cd (BaseThreadInitThunk+0x000d)
>   000000000022ffd0: 000000007702a561 (RtlUserThreadStart+0x0021)

**Comment by Tafoid** [comment]
I cannot reproduce this.  There is a step missing in your instructions above in which you need to select the slot where the cartridge resides (after your listed step 3), before being able to move on to the step 4 directions.  I do not get an exception or any fatal error showing up.  I can load another game from the software list (tested 2 different games: bonk, zeldalnk) successfully.

**Comment by Tauwasser** [comment]
The version I tested was latest HEAD (d3150b00903970beccd1a75bd0029297c45c2eed).

You're right about the step, you have to click the slot first, sorry about that.

When you say you could load another game, did you actually wait to see the GameBoy logo? Due to #2414, it still won't load the game even when it doesn't crash. Apparently there is some randomness to this, as I had it crash multiple times with the `basic_string::_M_replace_aux` message as well as multiple times with an access violation.

Maybe some buffer is used after free and depending on its contents it either crashes, makes an illegal access or works out because the memory isn't invalid yet? What would you need from me to debug this some more?

**Comment by npwoods** [comment]
I can't reproduce this either

**Comment by Tauwasser** [comment]
Sarayan could repro the exception (not the stacktrace) earlier in chat, so maybe he can add some information. Both errors at least point to some bug in processing strings, so maybe it's locale-specific (although I have US-English set for everything).

**Comment by galibert** [comment]
I was able to reproduce the fact that chaging software didn't work, but not
the crash.  The one I was able to reproduce was the one when starting from
nothing which is supposedly fixed now.

  OG.

**Comment by Tauwasser** [comment]
I just pulled latest HEAD (030ab611937bbaafb9d3f7144b2ab031add9d3c6) and it still happens, but now it doesn't crash to console immediately, but presents the same error in a message box:

![mame_error](https://user-images.githubusercontent.com/9909021/27602369-d6f77db6-5b72-11e7-959b-fe0daf2e39c8.png)

**Comment by Robbbert** [comment]
Using current git produces no error or crash with loading software here. Exactly what version of MAME are you using? That message box is not from normal MAME.

**Comment by Tauwasser** [comment]
I compiled myself with only GameBoy, but I confirmed it happens when I do a full regular build from a clean directory as well. [I used make clean as well as deleting the complete build folder and executables.] So I don't think it matters what machine support I compile in. I'm not sure why nobody else has this problem. I use the official msys2 download from the mame site and updated using pacman.

Here's the same screen from the full build:

![mess_error](https://user-images.githubusercontent.com/9909021/27687070-ae9faac8-5cd5-11e7-8bfb-834421a01496.png)

**Comment by Tauwasser** [comment]
This problem seems to be gone in master when using HEAD 229959ee7d. I didn't change anything in my build system and rebuilt with `make clean SUBTARGET=gb && make -j 8 REGENIE=1 SUBTARGET=gb` where gb is my gameboy-only target. Definitely something else caused the issue.

**Comment by Robbbert** [comment]
I was able to produce message boxes from MAME. You have to double-click mame.exe from Windows Explorer for message boxes to be enabled. To see one, select V-Smile in the menu, start it, and a message box appears.

Now, since the problem has gone away, I will close this. Thanks for letting us know.
