### ISSUE TITLE
SH-4 core has inverted 32-bit words in double-precision FPRs

### ISSUE THREAD

**Issue by MooglyGuy** [mamedev/mame#4139]
MAME's SH-4 core assumes that one can simply cast a float pointer to a double pointer and have the individual 32-bit words land in the correct order. This is not, nor has it ever been, a safe assumption.

Among surely other bugs, this causes the car Pole Position in Namco Museum on the Dreamcast pointed to the left. If and when this bug is fixed, it will point directly ahead.

**Comment by snickerbockers** [comment]
It looks like the problem is that when the sh4 code calls into a cfunc, it only saves the general-purpose registers to their backing and none of the FPU registers.  If the cfunc makes any changes to the FPU registers, then m_fd_regmap, m_fs_regmap, and m_sh2_state->m_fr will all become inconsistent with each other.

Having said that, there's an even bigger problem which is that the DRC doesn't seem to be aware that the double-precision registers and the single-precision registers are supposed to be overlapped.  They're created as two separate mappings to the same backing: https://github.com/mamedev/mame/blob/master/src/devices/cpu/sh/sh4.cpp#L2233.

Right now I have this fixed in my fork at https://github.com/snickerbockers/mame/commit/977d99ed6332849065857c30bbb43dc3c7bfdcb5 by replacing all the FPU instructions with cfuncs; that way the FR and DR register sets are always consistent because they're never accessed through UML.

I think the best way to fix this is to include the PR bit and the SZ bit into the hash for each code block, and make each code block end whenever it encounters an instruction that might toggle either of those bits (and maybe also instructions that might toggle the FR bit, which does bank-switching).  This will also solve the problem of needing to do a conditional jump and an unconditional jump in every FPU opcode.

Also discovered that this bug is preventing Hanagumi Taisen Columns 2 from booting with the DRC enabled.  When this is fixed, that title will be in-game.

**Comment by angelosa** [comment]
Still happening as in 0.228

**Comment by kibunn0307** [comment]
CPUが早くします。

**Comment by MooglyGuy** [comment]
Please favor English when leaving comments on Github issues. Additionally, the assertion that "the CPU will be faster" is not necessarily true, in fact any additional overhead will likely reduce overall speed.

**Comment by kibunn0307** [comment]
CPU SH4 FPR BUG Fixed OK

**Comment by MooglyGuy** [comment]
Stop posting.

**Comment by cuavas** [comment]
> CPUが早くします。

Hey, I already made it substantially faster this year already by optimising the generated code.  Your wish was granted before you asked!

**Comment by kibunn0307** [comment]
SH4 core bug Fixed in Version 0.282GIT OK YES。

**Comment by cuavas** [comment]
> It looks like the problem is that when the sh4 code calls into a cfunc, it only saves the general-purpose registers to their backing and none of the FPU registers. If the cfunc makes any changes to the FPU registers, then m_fd_regmap, m_fs_regmap, and m_sh2_state->m_fr will all become inconsistent with each other.

That was a bug affecting Linux and macOS, but not Windows.  It’s fixed (i.e. it no longer lets the UML FP registers get clobbered across C calls) at the cost of some performance.  I can refactor it to get the performance back, but that requires effort.

> I think the best way to fix this is to include the PR bit and the SZ bit into the hash for each code block, and make each code block end whenever it encounters an instruction that might toggle either of those bits (and maybe also instructions that might toggle the FR bit, which does bank-switching). This will also solve the problem of needing to do a conditional jump and an unconditional jump in every FPU opcode.

What’s it currently using the mode bits for?  If it doesn’t already have an excessive number of modes, it could potentially be used for floating point modes.

**Comment by MooglyGuy** [comment]
Well, since the issue is fixed, I'll close this.

**Comment by cuavas** [comment]
I think the original issue still exists.  The problem @snickerbockers was seeing with UML FP registers getting nuked is separate, and didn’t affect Windows – that’s the only part that’s fixed.

**Comment by angelosa** [comment]
<img width="711" height="480" alt="Image" src="https://github.com/user-attachments/assets/bc1ab753-0a8f-49fa-bc5a-dcaafd1d79cd" />

Ignores analog stick, only digital works (still decenters greatly).

**Comment by rb6502** [comment]
So what's actually broken?  The original report isn't all that clear, which is part of why this never was fixed.  (Also Naomi wasn't playably fast until recently).

**Comment by cuavas** [comment]
> So what's actually broken? The original report isn't all that clear, which is part of why this never was fixed. (Also Naomi wasn't playably fast until recently).

OK, the SH-4 FPU is old-school to put it nicely.

SH-2 only supports single precision (32-bit) FP.  The SH-4 adds double-precision (64-bit) support by overlaying 64-bit FP registers over pairs of 32-bit FP registers.  Each 64-bit FP register is aliased to two 32-bit FP registers.

The SH-4 doesn’t add extra double-precision FP instructions.  The PR (precision mode) bit in FPSCR controls whether FP arithmetic instructions operate on 32-bit registers or 64-bit registers.

On top of that, there’s also the SZ (transfer size) bit in FPSCR that controls whether FMOV does 32-bit or 64-bit transfers.  But when set to 64-bit, it always uses big Endian order for the two 32-bit halves, so it doesn’t do what you likely want if the CPU is in little Endian mode.

Also, SH-4 has two banks of FP registers and 4×32-bit FP SIMD operations with more fun aliasing to think about.

MAME doesn’t emulate this properly.  The aliasing doesn’t come out right, and it gets Endianness wrong for various operations.  I can’t recall what all the exact proper behaviour versus what MAME does cases are because it’s ages since I looked at it.  And yeah, it’s starting to matter more now that MAME can emulate SH-4 CPUs at decent speeds on 64-bit ARM hosts.

**Comment by p1pkin** [comment]
@cuavas do you have examples where endianness wrong in current code? on quick sight it looks right for me

@rb6502 SH-4's FPU is a bit odd, especially from little endian host point of view, mainly because it's internally BE and it seems developers wasn't able to made in time proper 64bit load/store in LE mode. it's became fully OK only in SH-4A arch, which got new SZ=1 PR=1 load/store mode.
it's good enough shown in SH-4A manual

<img width="995" height="781" alt="Image" src="https://github.com/user-attachments/assets/fa7d5c37-0189-4d3e-848f-9d2f3f9e0f8f" />

**Comment by angelosa** [comment]
On further check this bug is -drc specific, it doesn't occur with the interpreter.

**Comment by rb6502** [comment]
The interpreter definitely has the endian bug, so I guess Moogly's original report that it's the cause of the Pole Position bug is wrong.

**Comment by kibunn0307** [comment]
SH-4's FPU fixed yes OK!。
